import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./_components/CartContext";
import CartSidebar from "./_components/CartSidebar"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mikadu-HandBags Luxury",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <CartSidebar /> 
          <main>{children}</main>
        </CartProvider>
      </body>
    </html>
  );
}